from agent import DocumentGenerator

def main():
    agent = DocumentGenerator()
    agent.setup_page_margins()
    agent.set_header("Research Report: The Mystery Genre")
    
    agent.add_title("The Anatomy of a Mystery Story")
    agent.add_paragraph("A comprehensive research report exploring the core elements, history, and impact of mystery fiction.", style="Subtitle")
    
    agent.add_paragraph("Generated by the Document Generator Agent", italic=True, align="center")
    agent.add_page_break()
    
    agent.add_section_heading("1. Introduction")
    agent.add_paragraph(
        "Mystery fiction is a loosely defined genre of writing that involves a crime or a puzzle being solved. "
        "The core of a mystery story is a secret that needs to be uncovered, usually revolving around a crime such as murder, theft, or kidnapping."
    )
    
    agent.add_section_heading("2. Core Elements of a Mystery Story", level=2)
    agent.add_paragraph("A successful mystery typically relies on a well-established set of elements that keep the reader engaged:")
    agent.add_bullet_list([
        "The Hook: A compelling crime or puzzle that starts the narrative.",
        "The Sleuth: A detective, amateur or professional, who leads the investigation.",
        "The Suspects: A cast of characters with motives and means.",
        "Clues and Red Herrings: True hints mixed with false trails to mislead the sleuth and the reader.",
        "The Reveal: The climax where the truth is finally uncovered."
    ])
    
    agent.add_section_heading("3. Historical Milestones", level=2)
    agent.add_paragraph("The mystery genre has evolved significantly over the past two centuries. Here is a timeline of key milestones:")
    
    table_data = [
        ["Era / Year", "Author", "Significant Work / Contribution"],
        ["1841", "Edgar Allan Poe", "'The Murders in the Rue Morgue' (First modern detective story)"],
        ["1887", "Arthur Conan Doyle", "'A Study in Scarlet' (Introduction of Sherlock Holmes)"],
        ["1920s - 1930s", "Agatha Christie", "The 'Golden Age' of Detective Fiction"],
        ["1930s - 1940s", "Raymond Chandler & Dashiell Hammett", "Hardboiled and Noir Fiction"]
    ]
    agent.add_table(table_data)
    
    agent.add_section_heading("4. Common Sub-genres", level=2)
    agent.add_paragraph("Mystery is a broad umbrella that covers several distinct sub-genres:", bold=True)
    agent.add_bullet_list([
        "Cozy Mysteries: Mild violence, amateur sleuths, often set in small towns.",
        "Hardboiled: Gritty realism, flawed detectives, often set in urban environments.",
        "Police Procedurals: Focuses on the realistic methods and procedures of law enforcement.",
        "Locked Room Mysteries: A crime committed under seemingly impossible circumstances."
    ])
    
    agent.add_page_break()
    agent.add_section_heading("5. Conclusion")
    agent.add_paragraph(
        "The mystery genre continues to thrive because it taps into the fundamental human desire to solve puzzles and see justice served. "
        "Through intricate plotting and memorable characters, mystery writers craft compelling narratives that stand the test of time."
    )
    
    output_filename = "Mystery_Story_Research.docx"
    agent.save(output_filename)
    print(f"Successfully generated '{output_filename}'")

if __name__ == "__main__":
    main()
