import json
import sys
from pathlib import Path
from carisma.skills.docx import DocxSkill


class DocumentAgent:
    def __init__(self):
        self.skills: dict[str, object] = {}
        self._register_skills()

    def _register_skills(self):
        templates_dir = Path(__file__).parent / "templates"
        self.skills["docx"] = DocxSkill(
            templates_dir=str(templates_dir) if templates_dir.exists() else None
        )

    def list_skills(self) -> list[dict]:
        return [
            {
                "name": skill.name,
                "description": skill.description,
            }
            for skill in self.skills.values()
        ]

    def execute(self, request: dict) -> dict:
        skill_name = request.get("skill", "docx")
        action = request.get("action")
        params = request.get("params", {})

        skill = self.skills.get(skill_name)
        if not skill:
            raise ValueError(f"Unknown skill: {skill_name}")

        return skill.execute(action, **params)

    def generate_document(self, spec: dict) -> str:
        self.execute({"skill": "docx", "action": "create", "params": {"template": spec.get("template")}})
        if spec.get("properties"):
            self.execute({"skill": "docx", "action": "set_properties", "params": spec["properties"]})
        if spec.get("margins"):
            self.execute({"skill": "docx", "action": "set_margins", "params": spec["margins"]})
        for element in spec.get("content", []):
            kind = element.pop("type")
            self.execute({"skill": "docx", "action": f"add_{kind}", "params": element})
        output_path = spec.get("output", "output.docx")
        result = self.execute({"skill": "docx", "action": "save", "params": {"output_path": output_path}})
        return result["path"]


def main():
    agent = DocumentAgent()

    if len(sys.argv) > 1:
        with open(sys.argv[1]) as f:
            spec = json.load(f)
        output = agent.generate_document(spec)
        print(f"Document generated: {output}")
        return

    print("Carisma Document Agent")
    print("Skills:", [s["name"] for s in agent.list_skills()])

    spec = {
        "properties": {"title": "Sample Document", "author": "Carisma Agent"},
        "margins": {"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        "content": [
            {"type": "heading", "text": "Sample Document", "level": 1},
            {"type": "paragraph", "text": "This is a sample document generated by the Carisma Document Agent.", "bold": True},
            {"type": "paragraph", "text": "This agent uses the docx skill to create professional documents."},
            {"type": "heading", "text": "Features", "level": 2},
            {"type": "list", "items": ["Headings and paragraphs", "Tables and lists", "Headers and footers", "Images and styling"]},
            {"type": "heading", "text": "Data Table", "level": 2},
            {"type": "table", "headers": ["Item", "Description", "Value"], "rows": [
                ["Item 1", "Description of item 1", "$100"],
                ["Item 2", "Description of item 2", "$200"],
                ["Item 3", "Description of item 3", "$300"],
            ]},
        ],
        "output": "output.docx",
    }
    output = agent.generate_document(spec)
    print(f"Document generated: {output}")


if __name__ == "__main__":
    main()
